### PR TITLE
Practicing a Pull Request 

### LINKED ISSUE #3: Practice Issue Request
Please add more images of tigers

### PR DESCRIPTION
**Pull request by laurenlarson**
Close #3

### CODE REVIEW

**Comment by alexander-held** [comment]
Hi @laurenlarson, the automatic CI test here found a spelling mistake, could you please have a look at this before we merge this?

**Comment by oshadura** [comment]
@laurenlarson could you please check why your continious integration is failing?

**Comment by laurenlarson** [comment]
Fixed the spelling error

**Review by alexander-held — APPROVED** [review]
Looks all good now, thank you!

**Pull request merged**
